# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coretan Kecil @showcheap
email: chip@sucipto.net
description: > # this means to ignore newlines until "baseurl:"
  Coretan kecil, catatan ringan oleh Sucipto Kunjungi blog utama saya di www.sucipto.net

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coretan.sucipto.net" # the base hostname & protocol for your site
twitter_username: showcheap
github_username:  showcheap

# Build settings
markdown: kramdown
